addr: ":8080"
ca_key: "./ca_key"
cert_validity: 8h

# Optional TLS configuration
# Uncomment to enable HTTPS
# tls:
#   cert: "./server.crt"
#   key: "./server.key"

client_id: "xxx.apps.googleusercontent.com"
client_secret: "xxx"
redirect_url: "http://localhost:8080/callback"

# Users: email -> role -> principals
users:
  alice@example.com:
    default: [root, admin]
    deploy: [deploy]
  bob@example.com:
    default: [developer]
    deploy: [deploy]
  charlie@example.com:
    default: [developer]
    admin: [root, admin]
    deploy: [deploy]
