schema = 3

[mod]
  [mod."cloud.google.com/go/compute/metadata"]
    version = "v0.3.0"
    hash = "sha256-hj2Xjlz3vj7KYONZO/ItclWGGJEUgo5EvMEkGPfQi1Q="
  [mod."github.com/coreos/go-oidc/v3"]
    version = "v3.17.0"
    hash = "sha256-b9dCq5GN5ac64UG23Rijv1qcmUZNcxb8DJQycAa96EQ="
  [mod."github.com/go-jose/go-jose/v4"]
    version = "v4.1.3"
    hash = "sha256-WfogdTIRu4yDtCVX5fzz/+kKVPwX/hXBl+nY31XFHNc="
  [mod."golang.org/x/crypto"]
    version = "v0.47.0"
    hash = "sha256-78iRvMmPZVTBrIk30yGpAO11kVC5TLR1zGW85gFLHk4="
  [mod."golang.org/x/oauth2"]
    version = "v0.34.0"
    hash = "sha256-5eqpGGxJ7FJsPmfRek6roeGmkWHBMJaWYXyz8gXJsS4="
  [mod."golang.org/x/sys"]
    version = "v0.40.0"
    hash = "sha256-KDe+wMr7dfMFwKMJEljzk+f82pQWFFPoFHivjD7qJGg="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
